---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 724775999267729408-EOGJALPJq4eSLkwQ5sYbdi9Skx0QekS
:access_token_secret: 7yv3cIbMihd6mr6NXKyqPdZRwwOyZM8MD1TMNEpSFaDeK
